FROM python:3.9
WORKDIR /app
COPY HelloWorld.py .
CMD ["python", "HelloWorld.py"]
# docker build -t helloworldtest .
# docker run -p 8080:80 --name firstdockertest helloworldtest
# Jupyter Notebook 8888:8888
# Streamlit 8501:8501